---
title: "Plots notches"
author:
  - name: "Tom Smith"
    affiliation: "Cambridge Centre for Proteomics"
date: "`r format(Sys.time(), '%d %B, %Y')`"
abstract: | 
  Here, we plot the notches per dataset
output:
  pdf_document:
  html_notebook: default
geometry: margin=1in
fontfamily: mathpazo
fontsize: 11pt
---

Load libraries
```{r setup, message=FALSE}

#### Load packages ####
library(camprotR)
library(ggplot2)
library(tidyverse)
library(MSnbase)
```

```{r}
psm_res <- readRDS('../results/psm_res.rds')
```

```{r}
notch_lower <- 4.25
notch_upper <- 5.75
```

```{r}
psm_res %>% names() %>% lapply(function(x){
  p1 <- plot_TMT_notch(psm_res[[x]], notch_lower=notch_lower, notch_upper=notch_upper) +
    xlab('Reporter ion\nintensity (log2)')
  p2 <- plot_TMT_notch(psm_res[[x]], notch_lower=notch_lower, notch_upper=notch_upper, facet_by_sample=TRUE) +
    xlab('Reporter ion\nintensity (log2)')
  
  ggsave(sprintf('../results/plots/%s_tmt_notch.png', x), p1, width=4, height=4)
  ggsave(sprintf('../results/plots/%s_tmt_notch_per_tag.png', x), p2, width=6, height=6)
  
  print(p1 + ggtitle(x))
  print(p2 + ggtitle(x))
  return(NULL)
})
```
```{r}
replicates <- psm_res[c('LOPIT_DC_U2OS_Rep1', 'LOPIT_DC_U2OS_Rep2', 'LOPIT_DC_U2OS_Rep3')]

thresholds <- c(0,5,10,15,20,30,40,50,60,75,100)

notch_per_filter <- sapply(replicates, function(replicate){
  
  replicate <- update_average_sn(replicate)
  replicate <- replicate[rowSums(is.na(exprs(replicate)))!=ncol(replicate),]

  sapply(thresholds, function(thresh){
    flt <- replicate[fData(replicate)$Average.Reporter.S.N>thresh,]
    get_below_notch(flt)
  })
})

notch_per_filter <- notch_per_filter %>% data.frame() %>% mutate(threshold=thresholds) %>%
  pivot_longer(cols=-threshold, values_to='sub_notch', names_to='Replicate') %>%
  separate(Replicate, into=c(NA, NA, NA, 'Replicate'), sep='_')

print(notch_per_filter)

p <- notch_per_filter %>%
  ggplot(aes(threshold, 100*sub_notch, group=Replicate, colour=Replicate)) +
  geom_point() +
  geom_line() +
  scale_colour_manual(values=get_cat_palette(6)[4:6], labels=1:3) +
  theme_camprot() +
  scale_y_continuous(limits=c(0, 5), breaks=seq(0,5,1)) +
  xlab('Minimum average signal/noise') +
  ylab('Sub-notch (%)')

print(p)
ggsave('../results/plots/PSM_SN_flt_frac_notch.png')
```

```{r}

n_features <- sapply(replicates, function(replicate){
  
  replicate <- update_average_sn(replicate)
  replicate <- replicate[rowSums(is.na(exprs(replicate)))!=ncol(replicate),]

  sapply(thresholds, function(thresh){
    flt <- replicate[fData(replicate)$Average.Reporter.S.N>thresh,]
    nrow(flt)
  })
})

n_features <- n_features %>% data.frame() %>% mutate(threshold=thresholds) %>%
  pivot_longer(cols=-threshold, values_to='n_features', names_to='Replicate') %>%
  separate(Replicate, into=c(NA, NA, NA, 'Replicate'), sep='_')

print(n_features)

p <- n_features %>%
  ggplot(aes(threshold, n_features, group=Replicate, colour=Replicate)) +
  geom_point() +
  geom_line() +
  scale_colour_manual(values=get_cat_palette(6)[4:6], labels=1:3) +
  theme_camprot() +
  scale_y_continuous(limits=c(0, 100000), breaks=seq(0,100000,25000)) +
  xlab('Minimum average signal/noise') +
  ylab('PSMs')

print(p)
ggsave('../results/plots/PSM_SN_flt_n_features.png')
```




  