---
title: "Inspect phospho-peptides"
output:
  html_document: default
  html_notebook: default
---

Here we parse the raw data and see how many phosphopeptides we have identified in our test yeast phospho-peptide enrichment
```{r}
suppressMessages(library(dplyr))

source("../../CamProt_R/Utility.R") # this should work fine so long as you have the CamProt_R repo in the same directory as this repo
source("../../CamProt_R/Phospho.R")

```

Read in raw data for phospho-peptides
```{r}
phospho_inf = "../raw/testing_phospho_enrichment/Anja_yeast_phospho_PSMs.txt"
phospho_psm <- read.delim(phospho_inf, stringsAsFactors=FALSE)
```

Parse the PTM scores and add filtered_* columns to detail filtering 
```{r}
#phospho_psm <- parsePTMScores(
#  phospho_psm, ptm_col="PhosphoRS.Best.Site.Probabilities")

#phospho_psm <- phospho_psm %>% filter(filtered_score!="") # The filtering doesn't actually take place until this step 
```

Remove the cRAP protein peptides
```{r}
phospho_psm <- removeCrap(phospho_psm)
```

```{r}
dim(phospho_psm)
```

```{r}
peptide_counts <- phospho_psm %>%
  mutate(Modifications=gsub('^(; )', '',
                              gsub('(; )?(N|C|M|Q)\\d{1,2}\\((Carbamidomethyl|Deamidated|Oxidation|Deamidated)\\)', '', 
                                   Modifications))) %>%
  mutate('Sequence'=toupper(Annotated.Sequence)) %>%
  group_by(Sequence, Modifications) %>%
  tally()


# Just checking the above horrible gsub removes all modifications other than Phospho
table(peptide_counts$Modifications[!grepl('Phospho', peptide_counts$Modifications)])

x <- peptide_counts %>%
  mutate(phosphorylated=ifelse(grepl('Phospho', Modifications),
                               'Phosphorylated', 'Not phosphoryalted')) %>%
  dplyr::select(-n) %>%
  group_by(phosphorylated) %>%
  tally() %>%
  spread(key=phosphorylated, value=n) %>%
  mutate(`Fraction phosphoryalted`=round(Phosphorylated/(
    Phosphorylated+`Not phosphoryalted`),3))

knitr::kable(x)


```
OK, all looks good. >50% of our peptides are phosphorylated.
```{r}
phospho_psm %>%
  mutate(phosphorylated=ifelse(grepl('Phospho', Modifications),
                               'Phosphorylated', 'Not phosphoryalted')) %>%
  ggplot(aes(log10(Intensity), colour=phosphorylated)) +
  geom_density() +
  theme_bw() +
  scale_colour_discrete(name='')
```

